# Generated by Django 3.0.5 on 2020-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewRegistrationModel',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('EmailID', models.EmailField(max_length=254, unique=True)),
                ('ContactNo', models.IntegerField(unique=True)),
                ('DOB', models.DateField()),
                ('Company_Name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('usertype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserThoughtModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=100)),
                ('Contact_no', models.IntegerField()),
            ],
        ),
    ]
