# Generated by Django 3.0.5 on 2020-05-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporateUserApp', '0002_usereventmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTechnicalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Technology', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=100)),
                ('Contact_no', models.IntegerField()),
            ],
        ),
    ]
