# Generated by Django 3.0.5 on 2020-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporateUserApp', '0003_usertechnicaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCelebrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Address', models.TextField(max_length=100)),
                ('DOB', models.DateField()),
                ('Contact_no', models.IntegerField()),
                ('EmailID', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserPropertyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('PropertType', models.CharField(max_length=20)),
                ('Proprty_title', models.CharField(max_length=20)),
                ('Area_in_size', models.IntegerField()),
                ('price', models.FloatField()),
                ('Address', models.TextField(max_length=100)),
                ('Contact_no', models.IntegerField()),
                ('EmailID', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserReferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=100)),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserShareMarketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Company_name', models.CharField(max_length=30)),
                ('ShareValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTravelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=100)),
                ('Traveldate', models.DateField()),
                ('Contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Technology', models.CharField(max_length=30)),
                ('work_exp', models.IntegerField(max_length=2)),
                ('Description', models.TextField(max_length=100)),
                ('Contact_no', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='UserTechnicalDetails',
            new_name='UserTechnicalDetailsModel',
        ),
    ]
