# Generated by Django 3.0.5 on 2020-05-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporateUserApp', '0004_auto_20200515_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatrimonialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userworkexperiencemodel',
            name='work_exp',
            field=models.IntegerField(),
        ),
    ]
