# Generated by Django 3.0.5 on 2020-08-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporateUserApp', '0005_auto_20200517_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercelebrationmodel',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usereventmodel',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usermatrimonialmodel',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userreferencemodel',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usersharemarketmodel',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userthoughtmodel',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usertravelmodel',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
